### ISSUE TITLE
Error Exercise 5 OnSSET Teaching Kit

### ISSUE THREAD

**Issue by dianajjaramillo** [KTH-dESA/Cluster-based_extraction_OnSSET#2]
I get the following error when running the plugin using data from [Exercise 5](https://onsset.github.io/teaching_kit/courses/module_2/Excercise%205/) of the OnSSET Teaching Kit.

**An error has occurred while executing Python code:**  

**_core.QgsProcessingException: Unable to execute algorithm Could not load source layer for INPUT: /_filepath_/Assist2\Substationdist.shp not found** 

Traceback (most recent call last):
  File "/_filepath_/gep_onsset/GEP_OnSSET.py", line 584, in run
    processing.run("qgis:statisticsbycategories", {
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/plugins/processing/tools/general.py", line 108, in run
    return Processing.runAlgorithm(algOrName, parameters, onFinish, feedback, context)
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/plugins/processing/core/Processing.py", line 168, in runAlgorithm
    raise QgsProcessingException(msg)
_core.QgsProcessingException: Unable to execute algorithm
Could not load source layer for INPUT: /_filepath_/Assist2\Substationdist.shp not found
 
Python version: 3.8.7 (default, Feb 10 2021, 09:04:08) [Clang 12.0.0 (clang-1200.0.32.29)]  
QGIS version: 3.16.5-Hannover Hannover, 58ba7c1ed6

**Comment by akorkovelos** [comment]
Hi @dianajjaramillo may I redirect you to [this repo](https://github.com/OnSSET/ClusterbasedExtraction) that is maintained regularly. Also, note that the plugin is compatible only with Qgis 3.10.X (3.10.7 is recommended) as indicated in the exersice. So please install the proper Qgis version and re-install the plugin from the repo linked above (same process). That should solve the issue. I hope this helps.
